public enum AnimationTrack
{
    Idle = 0,
    Run = 1,
    Jump = 2,
    Fall = 3,
    WallCling = 4,
    TakeHit = 5,
    AttackStand = 6,
    AttackRun = 7,
    AttackJump = 8,
    IdlePreHenshin = 9,
    Henshin = 10,
    Death = 11,
    AttakWallCling = 12,
    AttackStandAlter = 13,
    AttackJumpAlter = 14,
    AttackStandUp = 15,
    AttackStandUpAlter = 16,
    GroundDash = 17,
    GroundDashAttack = 18,
    AirDash = 19,
    AirDashUp = 20,
    AirDashAttack = 21
}
